import axios from "axios";

let hostname = 'https://' + location.hostname;
// let hostname = 'http://' + location.hostname;
// let hostname = 'http://' + location.hostname+'/moe/public';
const gemsname=  [
        {
            name: "Diamond စိန်",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Ruby ပတ္တမြား",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Jade ကျောက်စိမ်း",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Emerald မြ",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Sapphire နီလာ",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Morganite မြပန်းရောင်",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Spinel အညံ့ပန်း",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Topaz ဥသ၁ဖယား/ ထပ်တရာ",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Zircon ဂေါ်မိတ်",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Bloodstone သွေးကျောက်",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },

        {
            name: "Coral သန္တာကျောက်",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Oryx မဟူရာ",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Turquoise စိမ်းပြာကျောက်",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Beryl မြကျောက်",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Garnet ဥဒေါင်",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Coral သန္တာကျောက်",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Moonstone လကျောက်",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Rose quartz ပန်းရောင်သလင်းကျောက်",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Aquamarine မြပြာ",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Amethyst ခရမ်းစွဲ",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Sodalite ကျောက်မျက်",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Tourmaline ဖရဲအူ",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Coral သန္တာကျောက်",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Peridot ပြောင်ခေါင်းစိမ်း",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Blue Star",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Agate သဘော်မဟူရာ",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "စလင်းဝါ",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "blue topaz",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Cat's Eye",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
        {
            name: "Pearl ပုလဲ",
            count: 0,
            carat: 0,
            yati: 0,
            pwint: 0,
            error: false,
        },
    ];


export const allstaticdata={
    gemsname:gemsname
 
}
